apiVersion: v1
kind: Service
metadata:
  name: billing-app
spec:
  selector:
    app: billing-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-app-sts
  labels:
    app: billing-app
spec:
  selector:
    matchLabels:
      app: billing-app
  template:
    metadata:
      labels:
        app: billing-app
    spec:
      initContainers:
        - name: init-container
          image: alpine:3.18
          command: ['sh', '-c', 'until nc -z -w 3 billing-db 5432; do echo waiting for billing-db; sleep 5; done;']
      containers:
        - name: billing-app
          image: ozennou/billing-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api-secret
          # resources:
          #   requests:
          #     cpu: "200m" # Specify the cpu resource to check the Horizontal scaling