apiVersion: v1
kind: Service
metadata:
  name: billing-db
spec:
  selector:
    app: billing-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-db-sts
  labels:
    app: billing-db
spec:
  selector:
    matchLabels:
      app: billing-db
  template:
    metadata:
      labels:
        app: billing-db
    spec:
      volumes:
        - name: billing-mount
          persistentVolumeClaim:
            claimName: billing-pvc
      containers:
        - name: billing-db
          image: ozennou/postgresql:latest
          ports:
            - containerPort: 5432
          securityContext:
            runAsUser: 70
            runAsGroup: 70
          volumeMounts:
            - name: billing-mount
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: [ 'pg_isready' ]
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: BILLING_DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: BILLING_DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: BILLING_DB_NAME
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: BILLING_DB_HOST
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: billing-pv
spec:
  capacity:
    storage: 150Mi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /home/amine/orchstrator-test/volume/billing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
  storageClassName: local-storage