apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: billing-queue
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-queue-deployment
  labels:
    app: billing-queue
spec:
  selector:
    matchLabels:
      app: billing-queue
  template:
    metadata:
      labels:
        app: billing-queue
    spec:
      containers:
        - name: billing-queue
          image: ozennou/rabbitmq:latest
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: RABBITMQ_PASSWD
            - name: RABBIT_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: RABBIT_EXCHANGE
            - name: RABBIT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: RABBIT_QUEUE